on:
  rss:
    url: https://steamcommunity.com/groups/freegamesfinders/rss/
jobs:
  beam:
    name: Beam to Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Send a Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Nuovo <b>gioco gratuito</b>:
            
            ${{on.rss.outputs.title}}
            ${{on.rss.outputs.link}}
          format: html
